repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
  - id: black-jupyter
    name: black-jupyter
    description:
      "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
    entry: black
    language: python
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi, jupyter]
    additional_dependencies: [".[jupyter]"]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
    - id: nbqa-pyupgrade
      args: ["--py38-plus"]
    - id: nbqa-isort
    - id: nbqa-flake8
      args: ["--extend-ignore=E402"]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify
    exclude: |
      (?x)^(
        scripts/old_plot_tests/|
        scripts/pathways_ms/
      )

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
      description: Strip output from jupyter notebooks
      args: [--drop-empty-cells]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: file-contents-sorter
      files: |
        (?x)^(
          .*requirements(-\w+)?.(in|txt)|
          MANIFEST.in
        )

- repo: https://github.com/regebro/pyroma
  rev: "4.1"
  hooks:
  - id: pyroma
    args: ["-d", "--min=10", "."]
    additional_dependencies:
    - numpy
    - cython

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.49"
  hooks:
  - id: check-manifest
    args: ["--ignore=.nox,build", "--no-build-isolation"]
    additional_dependencies:
    - numpy
    - cython
