# Converged source/sink field, 1984-2004.
#
# GENERATED by scripts/input_prep/7-source-sink/export_be_calibration.py
# from hatteras_site_config.py, which is the source of truth. Do not
# edit this file: edit the config, or re-run the calibration.
#
# Frozen-zone masked iteration, converged 2026-08-25. Domains outside the frozen zone set carry
# 0.0 because they were never eligible for correction, NOT because
# their residual was zero -- see be_calibration_domains.csv.

DOMAIN_BE_RATES_CALIBRATED = {
      1: -41.8,  # LOCKED — end domain, LRR-solved; see the end-domain note above
      2: +0.0,  # Cape Point / Shoal Dynamics
      3: +0.0,  # Cape Point / Shoal Dynamics
      4: +0.0,  # Cape Point / Shoal Dynamics
      5: +1.5,  # Cape Point / Shoal Dynamics | RESERVED for the groin module
      6: +2.2,  # Cape Point / Shoal Dynamics | RESERVED for the groin module
      7: +0.8,  # Cape Point / Shoal Dynamics | RESERVED for the groin module
      8: +1.8,  # Cape Point / Shoal Dynamics
      9: +0.0,  # Cape Point / Shoal Dynamics
     10: -2.4,  # Cape Point / Shoal Dynamics
     11: -1.6,  # Buxton–Avon Transition
     12: -1.7,  # Buxton–Avon Transition
     13: -1.0,  # Buxton–Avon Transition
     14: +0.0,  # Buxton–Avon Transition
     15: +0.0,  # Buxton–Avon Transition
     16: +0.0,  # Buxton–Avon Transition
     17: +0.0,  # Buxton–Avon Transition
     18: +0.0,  # Buxton–Avon Transition
     19: +0.0,  # Buxton–Avon Transition
     20: +0.0,  # Buxton–Avon Transition
     21: +0.0,  # Avon
     22: +0.3,  # Avon
     23: +0.0,  # Avon
     24: +0.0,  # Avon
     25: +0.0,  # Avon
     26: +0.0,  # Avon
     27: +0.9,  # Avon
     28: +1.2,  # Avon
     29: +2.3,  # Avon
     30: +3.3,  # Avon
     31: +3.8,  # Avon
     32: +3.3,  # Mid-island
     33: +1.7,  # Mid-island
     34: +1.2,  # Mid-island
     35: +0.0,  # Mid-island
     36: +0.0,  # Mid-island
     37: +0.0,  # Mid-island
     38: +0.0,  # Mid-island
     39: +0.0,  # Mid-island
     40: +0.0,  # Mid-island
     41: +0.0,  # Mid-island
     42: +0.0,  # Mid-island
     43: +0.0,  # Mid-island
     44: +0.3,  # Mid-island
     45: +0.0,  # Mid-island
     46: +0.0,  # Mid-island
     47: +0.0,  # Mid-island
     48: -0.4,  # Mid-island
     49: -1.1,  # Mid-island
     50: -2.1,  # Mid-island
     51: -2.4,  # Mid-island
     52: -2.2,  # Mid-island
     53: -2.0,  # Mid-island
     54: -1.8,  # Mid-island
     55: -1.0,  # Mid-island
     56: -1.0,  # Mid-island
     57: -0.3,  # Mid-island
     58: +0.0,  # Mid-island
     59: +0.0,  # Mid-island
     60: +0.0,  # Wimble Shoals Influence
     61: +0.0,  # Wimble Shoals Influence
     62: +0.0,  # Wimble Shoals Influence
     63: +0.0,  # Wimble Shoals Influence
     64: +0.0,  # Wimble Shoals Influence
     65: +0.0,  # Wimble Shoals Influence
     66: +0.0,  # Wimble Shoals Influence
     67: +0.0,  # Wimble Shoals Influence
     68: +0.6,  # Wimble Shoals Influence
     69: +1.7,  # Wimble Shoals Influence
     70: +2.2,  # Wimble Shoals Influence
     71: +3.0,  # Wimble Shoals Influence
     72: +3.7,  # Wimble Shoals Influence
     73: +3.8,  # Wimble Shoals Influence
     74: +3.4,  # Wimble Shoals Influence
     75: +1.9,  # Tri-Village / Rodanthe
     76: +0.0,  # Tri-Village / Rodanthe
     77: +0.0,  # Tri-Village / Rodanthe
     78: -1.1,  # Tri-Village / Rodanthe
     79: -2.0,  # Tri-Village / Rodanthe
     80: -3.2,  # Tri-Village / Rodanthe
     81: -3.8,  # Tri-Village / Rodanthe
     82: -4.2,  # Tri-Village / Rodanthe
     83: -4.5,  # Tri-Village / Rodanthe
     84: -4.6,  # Pea Island NWR
     85: -4.5,  # Pea Island NWR
     86: -3.8,  # Pea Island NWR
     87: -2.9,  # Pea Island NWR
     88: -2.2,  # Pea Island NWR
     89: -1.3,  # Pea Island NWR
     90: +26.8,  # LOCKED — end domain, LRR-solved; see the end-domain note above
}
