# ==============================================================================
# hat_source_sink.py
#
# WHERE DOES THE SOURCE/SINK (BACKGROUND EROSION) CALIBRATION LIVE?
#
# WHY THIS EXISTS
#   Seven scripts under scripts/input_prep/7-source-sink/ built
#   data/hatteras_init/7-source-sink/... by hand, and two of them had to agree
#   on the same pass-0 backup file with a "keep the two in step" comment -- one
#   of which pointed at a file that did not exist. Same answer as
#   hat_observed_rates.py for 5-scr: the location is resolved ONCE (2026-09-18).
#
#   The field the MODEL runs on is not here: it is a dict literal in
#   hatteras_site_config.py. These are the fit's own products, its figures,
#   and the exported copy of the field.
#
# THE LAYOUT, whose numbers match the script steps in
# scripts/input_prep/7-source-sink/ (1-prepare writes into output/raw_runs/,
# so it has no folder here)
#
#     data/hatteras_init/7-source-sink/
#         README.md                 generated by 4-export; describes the field
#         2-calibrate/
#             <pair>/               what one fit wrote: DOMAIN_BE_RATES*.txt,
#                                   be_zone_metrics.csv, cascade_base_lrr.csv,
#                                   convergence_history.json
#             prebe/                hatteras_site_config backups taken before
#                                   each apply pass
#         3-figures/
#             <pair>/1-field/  2-method/  3-limits/
#         4-export/                 be_rates_<period>.py and
#                                   be_calibration_domains.csv (default pair)
#         archive/                  superseded_20260825/, _20260902/, _20260914/
#
# A PAIR IS TWO CALIBRATION PERIODS FITTED JOINTLY, named
# <p1start>_<p1end>__<p2start>_<p2end>, e.g. 1984_2004__2004_2024. Until
# 2026-09-18 the default pair wrote to the ROOT of 2-calibrate/ and 3-figures/
# and only other pairs got a folder, so what the unlabelled files belonged to
# had to be known rather than read. Every pair has a folder now.
# ==============================================================================

from __future__ import annotations

from pathlib import Path

_HERE = Path(__file__).resolve()
PROJECT_ROOT = next(_p for _p in _HERE.parents
                    if (_p / "pyproject.toml").exists())
INIT_ROOT = PROJECT_ROOT / "data" / "hatteras_init"

BE_ROOT = INIT_ROOT / "7-source-sink"
CALIBRATE_ROOT = BE_ROOT / "2-calibrate"
FIGURES_ROOT = BE_ROOT / "3-figures"
EXPORT_DIR = BE_ROOT / "4-export"
ARCHIVE = BE_ROOT / "archive"

# Config backups written by HAT_be_apply_fit_to_config.py before each pass.
# Shared by every pair: a backup is of the whole config, not of one fit.
PREBE_DIR = CALIBRATE_ROOT / "prebe"

# The field as it stood before PASS 1 of the frozen-zone masked iteration,
# i.e. the one-shot (pass-0) solve. HAT_plot_be_zones.py and
# HAT_export_be_calibration.py both split each final rate into pass-0 plus
# what the iteration added, and must read the same file to agree.
PASS0_BACKUP = PREBE_DIR / "hatteras_site_config_prebe_20260914_180700.py"

DEFAULT_PERIOD_STARTS = (1984, 2004)
DEFAULT_PAIR_TAG = "1984_2004__2004_2024"


def pair_tag(p1_start, p1_end, p2_start, p2_end):
    """The folder name for a jointly fitted pair of periods."""
    return f"{p1_start}_{p1_end}__{p2_start}_{p2_end}"


def calibrate_dir(tag=DEFAULT_PAIR_TAG):
    """Where one pair's fit writes its tables and convergence history."""
    return CALIBRATE_ROOT / tag


def figures_dir(tag=DEFAULT_PAIR_TAG):
    """Where one pair's figures go (1-field/, 2-method/, 3-limits/ inside)."""
    return FIGURES_ROOT / tag


if __name__ == "__main__":
    for name in ("BE_ROOT", "CALIBRATE_ROOT", "FIGURES_ROOT", "EXPORT_DIR",
                 "ARCHIVE", "PREBE_DIR", "PASS0_BACKUP"):
        path = globals()[name]
        print(f"{'ok' if path.exists() else 'MISSING':8} {name:15} "
              f"{path.relative_to(PROJECT_ROOT).as_posix()}")
    pairs = sorted(p.name for p in CALIBRATE_ROOT.glob("*__*") if p.is_dir())
    print(f"{'':8} {'pairs':15} {', '.join(pairs) or 'none'}")
